doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        # metadata_cache_driver:
        #     type: pool
        #     pool: doctrine.system_cache_pool
        # query_cache_driver:
        #     type: pool
        #     pool: doctrine.system_cache_pool
        # result_cache_driver:
        #     type: pool
        #     pool: doctrine.result_cache_pool
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Application/Entity"
                prefix: 'App\Application\Entity'
                alias: App
